# Generated by Django 4.2.7 on 2025-08-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_capacity', models.IntegerField(default=1)),
                ('current_bookings', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='services.service')),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('service', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('appointment_datetime', models.DateTimeField()),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('ELDERLY', 'Elderly'), ('DISABLED', 'Disabled'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=15)),
                ('predicted_wait_minutes', models.IntegerField(default=0)),
                ('actual_wait_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.serviceslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
